// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// profile_read //
// ------------ //

#define profile_read_wrap_target 0
#define profile_read_wrap 5
#define profile_read_pio_version 0

static const uint16_t profile_read_program_instructions[] = {
            //     .wrap_target
    0x00c0, //  0: jmp    pin, 0
    0x4008, //  1: in     pins, 8
    0x8020, //  2: push   block
    0x00c5, //  3: jmp    pin, 5
    0x0003, //  4: jmp    3
    0xa042, //  5: nop
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program profile_read_program = {
    .instructions = profile_read_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = profile_read_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config profile_read_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + profile_read_wrap_target, offset + profile_read_wrap);
    return c;
}

static inline void profile_read_program_init(PIO pio, uint sm, uint offset, uint data_base_pin, uint strb_pin) {
    pio_sm_config c = profile_read_program_get_default_config(offset);
    // Set IN base to the start of the 8-bit data bus
    sm_config_set_in_pins(&c, data_base_pin);
    // Set the JMP pin to the STRB pin
    sm_config_set_jmp_pin(&c, strb_pin);
    // The direction of the 8 data pins is set to INPUT
    pio_sm_set_consecutive_pindirs(pio, sm, data_base_pin, 8, false);
    // Set shift direction to right (or left depending on D0-D7 ordering)
    // Auto-push is disabled (we push manually after waiting for edge)
    sm_config_set_in_shift(&c, true, false, 8);
    // Join FIFOs to give a deeper RX FIFO (8 words instead of 4)
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    pio_sm_init(pio, sm, offset, &c);
}

#endif

// ------------- //
// profile_write //
// ------------- //

#define profile_write_wrap_target 0
#define profile_write_wrap 5
#define profile_write_pio_version 0

static const uint16_t profile_write_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0x6009, //  1: out    pins, 9
    0x00c2, //  2: jmp    pin, 2
    0x00c5, //  3: jmp    pin, 5
    0x0003, //  4: jmp    3
    0xa042, //  5: nop
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program profile_write_program = {
    .instructions = profile_write_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = profile_write_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config profile_write_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + profile_write_wrap_target, offset + profile_write_wrap);
    return c;
}

static inline void profile_write_program_init(PIO pio, uint sm, uint offset, uint data_base_pin, uint strb_pin) {
    pio_sm_config c = profile_write_program_get_default_config(offset);
    // Set OUT base to the start of the 8-bit data bus + parity
    sm_config_set_out_pins(&c, data_base_pin, 9);
    // Set the JMP pin to the STRB pin
    sm_config_set_jmp_pin(&c, strb_pin);
    // The direction of the 9 data pins is set to OUTPUT
    pio_sm_set_consecutive_pindirs(pio, sm, data_base_pin, 9, true);
    sm_config_set_out_shift(&c, true, false, 16);
    // Join FIFOs to give a deeper TX FIFO (8 words instead of 4)
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    pio_sm_init(pio, sm, offset, &c);
}

#endif

